name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Pega o c√≥digo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive   # essencial para Hugo Modules

      # 2. Configura Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # 3. Baixa Hugo Modules (PaperMod)
      - name: Initialize + Update Hugo modules
        run: |
          hugo mod init ${{ github.repository }} || true
          hugo mod get -u

      # 4. Build do site
      - name: Build
        run: hugo --minify --baseURL "https://victormnalves.github.io/"

      # 5. Deploy para branch gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages      # <- branch separada
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
